package exception;

public class ErrorMessage {

    // Request
    public static final String BAD_REQUEST = "요청 형식이 올바르지 않습니다.";
    public static final String INVALID_REQUEST_DATA = "요청에 필요한 데이터가 존재하지 않습니다.";
    public static final String INVALID_REQUEST_FORMAT = "올바르지 않은 데이터 형식 입니다.";

    // DB Connection
    public static final String INVALID_DB_CONNECTION = "DB 연결 정보가 올바르지 않습니다.";
    public static final String CONNECTION_POOL_IS_FULL = "커넥션 풀이 가득 찼습니다, 새로운 커넥션을 만들 수 없습니다.";

    // DB Service
    public static final String FAILED_AUTOGENERATED_ID_FIND = "Can not Find autogenerated ID";

    public static final String FAILED_STADIUM_FIND = "야구장이 존재하지 않습니다.";

    public static final String FAILED_TEAM_FIND = "팀이 존재하지 않습니다.";

    public static final String FAILED_OUT_PLAYER_REGISTRATION = "퇴출 선수 등록에 실패하였습니다";

    public static final String FAILED_PLAYER_REGISTRATION = "선수 등록에 실패 하였습니다.";
    public static final String FAILED_PLAYER_UPDATE = "선수 정보 변경을 실패 하였습니다.";
    public static final String FAILED_PLAYER_FIND = "선수 조회에 실패 하였습니다.";
    public static final String FAILED_PLAYER_UPDATE_SQL = "Failed to Update player while execute SQL";
    public static final String FAILED_PLAYER_REGISTRATION_SQL = "Failed to Register Out player while execute SQL";

}
